/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarteraRouteImport } from './routes/cartera'
import { Route as ConsejosRouteImport } from './routes/consejos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as SolicitudesRouteImport } from './routes/solicitudes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteraRoute = CarteraRouteImport.update({
  id: '/cartera',
  path: '/cartera',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsejosRoute = ConsejosRouteImport.update({
  id: '/consejos',
  path: '/consejos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudesRoute = SolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cartera': typeof CarteraRoute
  '/consejos': typeof ConsejosRoute
  '/perfil': typeof PerfilRoute
  '/solicitudes': typeof SolicitudesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cartera': typeof CarteraRoute
  '/consejos': typeof ConsejosRoute
  '/perfil': typeof PerfilRoute
  '/solicitudes': typeof SolicitudesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cartera': typeof CarteraRoute
  '/consejos': typeof ConsejosRoute
  '/perfil': typeof PerfilRoute
  '/solicitudes': typeof SolicitudesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/cartera' | '/consejos' | '/perfil' | '/solicitudes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/cartera' | '/consejos' | '/perfil' | '/solicitudes'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cartera'
    | '/consejos'
    | '/perfil'
    | '/solicitudes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CarteraRoute: typeof CarteraRoute
  ConsejosRoute: typeof ConsejosRoute
  PerfilRoute: typeof PerfilRoute
  SolicitudesRoute: typeof SolicitudesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartera': {
      id: '/cartera'
      path: '/cartera'
      fullPath: '/cartera'
      preLoaderRoute: typeof CarteraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consejos': {
      id: '/consejos'
      path: '/consejos'
      fullPath: '/consejos'
      preLoaderRoute: typeof ConsejosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitudes': {
      id: '/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof SolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CarteraRoute: CarteraRoute,
  ConsejosRoute: ConsejosRoute,
  PerfilRoute: PerfilRoute,
  SolicitudesRoute: SolicitudesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
